// Generated by BUCKLESCRIPT VERSION 4.0.1100, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("/Users/jim/Github/reasonml-gol/node_modules/bs-jest/src/jest.js");
var GameOfLife = require("./GameOfLife.bs.js");

describe("Game of lyfe", (function (param) {
        Jest.test("createGrid of 2", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* array */[
                              /* Dead */0,
                              /* Dead */0
                            ],
                            /* array */[
                              /* Dead */0,
                              /* Dead */0
                            ],
                            /* array */[
                              /* Dead */0,
                              /* Dead */0
                            ]
                          ], Jest.Expect[/* expect */0](GameOfLife.createGrid(2, 3)));
              }));
        Jest.test("randomizeGrid with seed 1", (function (param) {
                var grid = /* array */[
                  /* array */[
                    /* Dead */0,
                    /* Dead */0
                  ],
                  /* array */[
                    /* Dead */0,
                    /* Dead */0
                  ]
                ];
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* array */[
                              /* Live */1,
                              /* Dead */0
                            ],
                            /* array */[
                              /* Live */1,
                              /* Live */1
                            ]
                          ], Jest.Expect[/* expect */0](GameOfLife.randomizeGrid(3, 0.3, grid)));
              }));
        Jest.test("countNeighbours", (function (param) {
                return Jest.Expect[/* toEqual */12](2, Jest.Expect[/* expect */0](GameOfLife.countNeighbours(/* tuple */[
                                    1,
                                    0
                                  ], /* array */[
                                    /* array */[
                                      /* Live */1,
                                      /* Dead */0
                                    ],
                                    /* array */[
                                      /* Dead */0,
                                      /* Dead */0
                                    ],
                                    /* array */[
                                      /* Dead */0,
                                      /* Live */1
                                    ]
                                  ])));
              }));
        return Jest.test("two cells die", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[/* array */[
                                    /* Dead */0,
                                    /* Dead */0
                                  ]], Jest.Expect[/* expect */0](GameOfLife.iterate(/* array */[/* array */[
                                            /* Live */1,
                                            /* Live */1
                                          ]])));
                    }));
      }));

/*  Not a pure module */
