// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/src/jest.js");
var GameOfLife$ReasonGameOfLife = require("./GameOfLife.bs.js");

describe("Game of lyfe", (function () {
        Jest.test("createGrid of 2", (function () {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* array */[
                              /* Dead */0,
                              /* Dead */0
                            ],
                            /* array */[
                              /* Dead */0,
                              /* Dead */0
                            ],
                            /* array */[
                              /* Dead */0,
                              /* Dead */0
                            ]
                          ], Jest.Expect[/* expect */0](GameOfLife$ReasonGameOfLife.createGrid(2, 3)));
              }));
        Jest.test("randomizeGrid with seed 1", (function () {
                var grid = /* array */[
                  /* array */[
                    /* Dead */0,
                    /* Dead */0
                  ],
                  /* array */[
                    /* Dead */0,
                    /* Dead */0
                  ]
                ];
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* array */[
                              /* Dead */0,
                              /* Live */1
                            ],
                            /* array */[
                              /* Dead */0,
                              /* Dead */0
                            ]
                          ], Jest.Expect[/* expect */0](GameOfLife$ReasonGameOfLife.randomizeGrid(0.3, grid, /* Some */[3])));
              }));
        Jest.test("countNeighbours", (function () {
                return Jest.Expect[/* toEqual */12](2, Jest.Expect[/* expect */0](GameOfLife$ReasonGameOfLife.countNeighbours(/* tuple */[
                                    1,
                                    0
                                  ], /* array */[
                                    /* array */[
                                      /* Live */1,
                                      /* Dead */0
                                    ],
                                    /* array */[
                                      /* Dead */0,
                                      /* Dead */0
                                    ],
                                    /* array */[
                                      /* Dead */0,
                                      /* Live */1
                                    ]
                                  ])));
              }));
        return Jest.test("two cells die", (function () {
                      return Jest.Expect[/* toEqual */12](/* array */[/* array */[
                                    /* Dead */0,
                                    /* Dead */0
                                  ]], Jest.Expect[/* expect */0](GameOfLife$ReasonGameOfLife.iterate(/* array */[/* array */[
                                            /* Live */1,
                                            /* Live */1
                                          ]])));
                    }));
      }));

/*  Not a pure module */
