// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Reprocessing = require("Reprocessing/src/Reprocessing.js");
var Reprocessing_Env = require("Reprocessing/src/Reprocessing_Env.js");
var Reprocessing_Draw = require("Reprocessing/src/Reprocessing_Draw.js");
var Reprocessing_Constants = require("Reprocessing/src/Reprocessing_Constants.js");

function setup(env) {
  return Reprocessing_Env.size(200, 200, env);
}

function draw(_, env) {
  Reprocessing_Draw.background(Reprocessing_Constants.black, env);
  Reprocessing_Draw.fill(Reprocessing_Constants.red, env);
  return Reprocessing_Draw.rect(/* tuple */[
              50,
              50
            ], 100, 100, env);
}

Reprocessing.run(setup, /* None */0, /* Some */[draw], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

exports.setup = setup;
exports.draw = draw;
/*  Not a pure module */
